# Generated by Django 4.1.4 on 2023-01-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SatsukiHome', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='messages',
            field=models.TextField(default='Just to Say Hi'),
        ),
    ]
