# Generated by Django 4.1.4 on 2023-01-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SatsukiHome', '0003_messages_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='username',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
