# Generated by Django 4.1.4 on 2023-01-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SatsukiHome', '0004_messages_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
